version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: think41_db
      POSTGRES_USER: think41_user
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://think41_user:yourpassword@db:5432/think41_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

volumes:
  db_data: